/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import daoMySQL.ConnexionMySQL;

/**
 *
 * @author E
 */
public class JFPrincipale extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipale
     */
    public JFPrincipale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemQ = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemA = new javax.swing.JMenuItem();
        jMenuItemC = new javax.swing.JMenuItem();
        jMenuItemE = new javax.swing.JMenuItem();
        jMenuItemL = new javax.swing.JMenuItem();
        jMenuItemP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        jMenu3.setText("Fichier");

        jMenuItemQ.setText("Quitter");
        jMenuItemQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemQ);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Editer");

        jMenuItemA.setText("Appareils");
        jMenuItemA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemA);

        jMenuItemC.setText("Catégories");
        jMenuItemC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemC);

        jMenuItemE.setText("Etats");
        jMenuItemE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemE);

        jMenuItemL.setText("Locaux");
        jMenu4.add(jMenuItemL);

        jMenuItemP.setText("Panne");
        jMenuItemP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemP);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAActionPerformed
        jDesktopPane1.removeAll();
        JIFAppareils f = new JIFAppareils();
        jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            System.out.println("Problème de maximize");
        }
        jDesktopPane1.repaint();
    }//GEN-LAST:event_jMenuItemAActionPerformed

    private void jMenuItemQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQActionPerformed
        ConnexionMySQL.getInstance().close();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemQActionPerformed

    private void jMenuItemCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCActionPerformed
        jDesktopPane1.removeAll();
        JIFCategories f = new JIFCategories();
        jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            System.out.println("Problème de maximize");
        }
        jDesktopPane1.repaint();
    }//GEN-LAST:event_jMenuItemCActionPerformed

    private void jMenuItemPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPActionPerformed
        jDesktopPane1.removeAll();
        JIFPannes f = new JIFPannes();
        jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            System.out.println("Problème de maximize");
        }
        jDesktopPane1.repaint();
    }//GEN-LAST:event_jMenuItemPActionPerformed

    private void jMenuItemEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEActionPerformed
        jDesktopPane1.removeAll();
        JIFEtats f = new JIFEtats();
        jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            System.out.println("Problème de maximize");
        }
        jDesktopPane1.repaint();
    }//GEN-LAST:event_jMenuItemEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipale.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemA;
    private javax.swing.JMenuItem jMenuItemC;
    private javax.swing.JMenuItem jMenuItemE;
    private javax.swing.JMenuItem jMenuItemL;
    private javax.swing.JMenuItem jMenuItemP;
    private javax.swing.JMenuItem jMenuItemQ;
    // End of variables declaration//GEN-END:variables
}
